name: Automatic-PythonMailSender
on:
  push:
    branches:
      - disabled
    paths:
      - 'template_clients.xlsx' 
      - '.github/workflows/auto-run-job.yaml' 

jobs:
  main-job:
    runs-on: ubuntu-latest   
    permissions:
      contents: write
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: run container with script
      run: |
          docker run --rm \
          -v $PWD:/data \
          -e libro_excel='/data/clients.xlsx' \
          -e hoja_de_trabajo='main_page' \
          -e tiempo_entre_cada_mail=2 \
          -e pais_zona_horaria='America/Argentina/Buenos_Aires' \
          -e SERVIDOR_SMTP="${{ secrets.SERVIDOR_SMTP }}" \
          -e PUERTO_SMTP="${{ secrets.PUERTO_SMTP }}" \
          -e SENDER="${{ secrets.SENDER }}" \
          -e PASSWORD="${{ secrets.PASSWORD }}"  \
          jpradoar/python_xls_mail_sender:latest python3 /data/sender.py
     
    - name: copy file
      run: |
        cp template_clients.xlsx new_clients.xlsx
        
    - uses: EndBug/add-and-commit@v9
      with:
        message: 'AutoCommit: autoupdate clients.xlsx file'
        add: 'new_clients.xlsx'               
