name: Automatic-PythonMailSender
on:
  push:
    branches:
      - main
    paths:
      - 'template_clients.xlsx' 
      - '.github/workflows/auto-run-job.yaml' 

jobs:
  main-job:
    runs-on: ubuntu-latest   
    permissions:
      contents: write
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: run container with script
      run: |
        docker run --rm \
        -v $PWD:/data \
        -e servidor_smtp='${{ secrets.SERVIDOR_SMTP }}' \
        -e puerto_smtp='${{ secrets.PUERTO_SMTP }}' \
        -e sender='${{ secrets.SENDER }}' \
        -e password='${{ secrets.PASSWORD }}' \        
        -e libro_excel='/data/clients.xlsx' \
        -e hoja_de_trabajo='main_page' \
        -e tiempo_entre_cada_mail=2 \
        -e pais_zona_horaria='America/Argentina/Buenos_Aires' \
        jpradoar/python_xls_mail_sender:latest python3 /data/sender.py
        
    - name: copy file
      run: |
        cp template_clients.xlsx new_clients.xlsx
        
    - uses: EndBug/add-and-commit@v9
      with:
        message: 'AutoCommit: autoupdate clients.xlsx file'
        add: '*.xlsx'               
