name: PythonMailSender
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'none'


env: 
  MSG_TIMEZONE: America/Argentina/Buenos_Aires
  LIBRO: /data/clients.xlsx
  HOJA: main_page
  MAIL_TIME: 2

jobs:
  main-job:
    runs-on: ubuntu-latest   
    permissions:
      contents: write
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: run container with script
      run: |
        docker run --rm \
        -v $PWD:/data \
        -e libro_excel='{{ env.LIBRO }}' \
        -e hoja_de_trabajo='{{ env.HOJA }}' \
        -e tiempo_entre_cada_mail={{ env.MAIL_TIME }} \
        -e pais_zona_horaria='{{ env.MSG_TIMEZONE }}' \
        -e servidor_smtp="{{ secret.SERVIDOR_SMTP }}" \
        -e puerto_smtp="{{ secret.PUERTO_SMTP }}" \
        -e sender="{{ secret.SENDER }}" \
        -e password="{{ secret.PASSWORD }}" \
        jpradoar/python_xls_mail_sender:latest python3 /data/sender.py

    - uses: EndBug/add-and-commit@v9
      with:
        message: 'AutoCommit: autoupdate clients.xlsx file'
        add: './clients.xlsx'        
